# Generated by Django 4.2.3 on 2023-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='image',
            field=models.TextField(null=True, verbose_name='Image'),
        ),
    ]
